version: "3"
services:
    app:
        image: golang:1.16
        volumes:
            - .:/app/
        working_dir: /app/
        command: go run main.go --port 8000 --skip-translation-fetch --config './data/config.json'
        ports:
            - "8000"
        environment:
            GOPATH: /home/$USER/go
            REDIS_URL: redis:6379
            POSTGRES_URL: postgres:5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_DATABASE: dbname
            POSTGRES_SSLMODE: disable
    nginx:
        image: nginx:latest
        volumes:
            - ./data/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "80:80"
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./data/prometheus/:/data/
        command:
            - "--config.file=/data/prometheus.yml"
        ports:
            - "9090:9090"
    redis:
        image: redis:latest
        command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: mysecretpassword 
            POSTGRES_DB: dbname
        ports:
            - "5432"
