version: "3"
services:
    app:
        image: golang:1.12.17
        volumes:
        - .:/app/
        working_dir: /app/
        command: go run main.go --port 8000 --skip-translation-fetch --config './data/config.json'
        ports:
            - "8000"
        environment:
            REDIS_URL: redis:6379
            JWT_SECRET: secret_secret
    nginx:
        image: nginx:latest
        volumes:
            - ./data/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "80:80"
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./data/prometheus/:/data/
        command:
            - "--config.file=/data/prometheus.yml"
        ports:
            - "9090:9090"
    redis:
        image: redis:latest
        command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]
